# https://aka.ms/yaml
queue: 'Hosted Linux Preview'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'

- script: python -m pip install --upgrade pip && pip install -r requirements.txt
  displayName: 'Install requirements'
- script: flake8 .
  displayName: 'Run lint tests'
- script: nosetests tests
  displayName: 'Run unittests'

- task: PublishTestResults@1
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Test results for Python $(python.version)'